apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "myapp"
          effect: "NoSchedule"
      containers:
        - name: myapp-backend
          image: 486408064722.dkr.ecr.us-east-1.amazonaws.com/front-back-end-services:{{BACKEND_TAG}}
          ports:
            - containerPort: 8080
          # Adjust probes to backend endpoint
          livenessProbe:
            httpGet:
              path: /api/hello
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/hello
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-backend-service
  namespace: default
spec:
  selector:
    app: myapp-backend
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080

