apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Frontend path
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: myapp-frontend-service
                port:
                  number: 80
          # Backend path
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: myapp-backend-service
                port:
                  number: 8080

